name: Do Nothing Tool - Varied

on:
  schedule:
    # Berjalan setiap hari jam 07:00 WIB (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Random Commits
        run: |
          # Menghasilkan angka acak antara 1 sampai 5
          num=$(( ( RANDOM % 5 )  + 1 ))
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          for i in $(seq 1 $num)
          do
            echo "Update ke-$i pada $(date)" > mark.txt
            git add mark.txt
            git commit -m "Progress update: $(date)"
          done
          
          git push
